name: Test Axonius Helpers

on:
  pull_request:
    types: [opened, reopened]
  
jobs:
  Test-Axonius-Helpers:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      
      - name: Set up Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0

      - name: Run Python tests script
        run: |
          python -m pip install --upgrade pip
          cd .github/workflows
          pip install -r requirements.txt
          python test_axonius_helpers.py
